# Generated by Django 2.1.4 on 2018-12-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='summary',
            new_name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='pub_date',
            field=models.DateField(null=True),
        ),
    ]
