# Generated by Django 2.1.4 on 2018-12-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181224_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
