# Generated by Django 2.1.4 on 2019-01-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_text',
            field=models.CharField(default='short description goes here', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
