# Generated by Django 2.1.4 on 2019-01-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190101_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='Image goes here', upload_to='images/'),
            preserve_default=False,
        ),
    ]
