# Generated by Django 2.1.5 on 2019-02-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190203_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='code_files',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
