# Generated by Django 2.1.5 on 2019-02-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blog_code_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='estilos_files',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
