# Generated by Django 2.1.5 on 2019-02-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blog_estilos_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='include_markdown',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
