# Generated by Django 2.1.5 on 2019-02-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_blog_include_markdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='body',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='include_markdown',
        ),
        migrations.AddField(
            model_name='blog',
            name='mdBody',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='rawBody',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
